version: '3'

services:
  consulserver01:
    image: consul:1.10
    networks:
      consul_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    container_name: consulserver01
    hostname: consulserver01
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./servers/server01:/etc/consul.d
    ports:
      - "8500:8500"
  consulserver02:
    image: consul:1.10
    networks:
      consul_net:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::11
    container_name: consulserver02
    hostname: consulserver02
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./servers/server02:/etc/consul.d
  consulserver03:
    image: consul:1.10
    networks:
      consul_net:
        ipv4_address: 172.16.238.12
        ipv6_address: 2001:3984:3989::12
    container_name: consulserver03
    hostname: consulserver03
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./servers/server03:/etc/consul.d
  consulclient01:
    image: consul:1.10
    networks:
      consul_net:
        ipv4_address: 172.16.238.13
        ipv6_address: 2001:3984:3989::13
    container_name: consulclient01
    hostname: consulclient01
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./clients/consul01:/etc/consul.d
  consulclient02:
    image: consul:1.10
    networks:
      consul_net:
        ipv4_address: 172.16.238.14
        ipv6_address: 2001:3984:3989::14
    container_name: consulclient02
    hostname: consulclient02
    command: [ 'tail', '-f', '/dev/null' ]
    volumes:
      - ./clients/consul02:/etc/consul.d

networks:
  consul_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
        - subnet: "2001:3984:3989::/64"
